language: ruby
rvm:
  - 1.9.3
before_script:
  - bash build/post_build.sh

env:
  global:
    - secure: "Y++xazjno1xaTnDZD7t/Xr+n2Y3j5SaUI0RnTIleaOsQsYqluDb+y9kGtuge\nFngzo81IuVrYcKbtwrnIenFNil0szkjAoYjDaKBeg4xztbtHB3lnlzWFqrG8\nSTGidwyPjA1H/PBnPwwyl+SXIKh91byjgTEDtwZefqFXMIV8Wxs="

branches:
  except:
    - gh-pages


script:
  - bash build/gh-pages-report.sh