disqus: wesleyhales
google_analytics: UA-1241000-10

profiles:
  development:
  production:
    base_url: http://www.wesleyhales.com/
    deploy:
      host: www.wesleyhales.com
      path: /home/wesley/www.wesleyhales.com
